FROM debian:latest
WORKDIR /app
COPY . .

RUN apt update \
    && apt upgrade \
    && apt install \
        python3 \
        pip \
        -y \
    && pip install psutil

EXPOSE 6000
CMD ["python3","main.py"]